on:
  pull_request:
    branches:
      - main
  workflow_dispatch: 

permissions:
  contents: write
  pull-requests: write

name: update-version

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          extra-files: |
            README.md
            CHANGELOG.md
